//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerKing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BurgerKingEntities1 : DbContext
    {
        public BurgerKingEntities1()
            : base("name=BurgerKingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Burger> Table_Burger { get; set; }
        public virtual DbSet<Table_Contact> Table_Contact { get; set; }
        public virtual DbSet<Table_Order> Table_Order { get; set; }
        public virtual DbSet<Table_Recuritment> Table_Recuritment { get; set; }
        public virtual DbSet<Table_Staff> Table_Staff { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
    }
}
