//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerKing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User
    {
        public int id { get; set; }
        public string Name_ID { get; set; }
        public string Password_ID { get; set; }
    }
}
